### ISSUE TITLE
mid60

### ISSUE THREAD

**Issue by Mr4g** [Rickedb/OpenProtocolInterpreter#103]
How do I change the revision I want to call through mid60

**Comment by Rickedb** [comment]
By default in version 6.0.0 all Mids are set to revision 1 when using the empty constructor. 
However set it by the another overload of the constructor `Mid0060(int revision, bool noAckFlag = false)`

**Comment by Mr4g** [comment]
![obraz](https://github.com/Rickedb/OpenProtocolInterpreter/assets/133530721/9f78bc28-a75d-4b2d-8e29-7d3af2c54c83)

doesn't work

**Comment by Rickedb** [comment]
Seems that you're not familiar with C#. 

Try: `new Mid0060(6, false)` or another possible option is: `new Mid0060(revision: 6, noAckFlag: false)`

**Comment by Mr4g** [comment]
you're right I'm just learning, but before that I also tried like you, but I forgot to pay attention to what parameter the constructor takes and noAckflag is of type int 

![obraz](https://github.com/Rickedb/OpenProtocolInterpreter/assets/133530721/b93ebbe5-5288-46e7-8592-e03841064989)

**Comment by Rickedb** [comment]
You're probably using an older version of the library which used to be an `int?`, versions 5.X.X or greater is boolean. 
But it's still the same approach.
