### ISSUE TITLE
MID 61 Tightening subscription successful, but package is not received when tightening is performed [Help needed, question]

### ISSUE THREAD

**Issue by SrividhyaRavichandran** [Rickedb/OpenProtocolInterpreter#114]
Program output:

Sending Tightening Subscribe...
Sending message: 00200060001         
Response: 00240005        00000060
Tightening Subscribe accepted!

Sending Keep Alive...
Sending message: 00209999            
Response: 00209999        0000
Keep Alive Received

**Atlas Copco PF 4000**. Tightening subscription is successful. But when i perform the tightening, below method is not getting executed. Any help in debugging will be highly appreciated. I am new to working with the controllers. Thank you

```csharp
protected virtual void OnPackageReceived(object sender, Message message)
{
    try
    {
        Console.WriteLine($"Message arrived: {message.MessageString}");

        var mid = this._midInterpreter.Parse(message.MessageString);
        var action = this.OnReceivedMID.FirstOrDefault(x => x.Key == mid.GetType());

        if (action.Equals(default(KeyValuePair<Type, ReceivedCommandActionDelegate>)))
        {
            Console.WriteLine($"NO ACTION WAS REGISTERED TO MID: {mid.GetType()}");
            return;
        }

        action.Value(new MIDIncome() { Mid = mid });
    }
    catch (Exception ex)
    {
        Console.WriteLine($"Exception: {ex.Message}");
    }
}
```

**Comment by Rickedb** [comment]
You need to set a Job at the controller, which could be done manually by setting it through the controller panel or via open protocol (if enabled).
Once done, if the tool is rotating the fuse when you trigger the tool's button, then it must send you Mid0061 if you're subscribed.

Unfortunately I don't have any documentation about of how to configure the controller physically. I only remember doing it by navigating on every setting at it and trying out

**Comment by SrividhyaRavichandran** [comment]
Thank you. I will check the tightening via jobs instead of psets. Your help is much appreciated :)
