### ISSUE TITLE
Mid0035 does not format new MID's the same way they are parsed.

### ISSUE THREAD

**Issue by NuAoA** [Rickedb/OpenProtocolInterpreter#12]
It appears that the JobId field packs as if it was revision 1 even if its a higher revision.

I believe this is due to the UpdateFieldsIndexBasedOnRevision() being only called on parse, and not when the mid is created via a constructor.

**Comment by Rickedb** [comment]
Could simulate the bug here.
Going to fix it, not sure if using the constructor approach. 
Also, this must be replicated to every mid that needs to update field sizes.

Thanks for the opened issue!

**Comment by Rickedb** [comment]
Fixed, version 3.0.3 now available
