### ISSUE TITLE
Missing Batch status 3 in MID 0061

### ISSUE THREAD

**Issue by ekdahl** [Rickedb/OpenProtocolInterpreter#18]
The Batch status value 3 is missing for MID 0061. This was added in version 2.9.0 of the standard and is used in newer firmware versions instead of 0 for running batches. Attached spec version 2.10
[Open Protocol Specification 2.10.pdf](https://github.com/Rickedb/OpenProtocolInterpreter/files/4165044/Open.Protocol.Specification.2.10.pdf)

**Comment by Rickedb** [comment]
Thanks for providing this. Going to add it.
It'll be available in the next release.

**Comment by Rickedb** [comment]
Version 3.0.5 deployed, will be soon available on NuGet.
