### ISSUE TITLE
Unit test failed.

### ISSUE THREAD

**Issue by HoytRen** [Rickedb/OpenProtocolInterpreter#47]
TestCustomMid.cs Line: 54 should be
            get => Time.ToString("dd'/'MM'/'yyyy HH:mm:ss");
Or the unit test could be failed. 
https://stackoverflow.com/questions/6343289/why-does-datetime-tostringdd-mm-yyyy-give-me-dd-mm-yyyy

**Comment by Rickedb** [comment]
Thanks for submiting the issue.
The way how it is now works, but Culture is always a problem. Going to fix!
