### ISSUE TITLE
StrategyOptionsConverter creates 10 instead of 5 bytes

### ISSUE THREAD

**Issue by IngeRuppio** [Rickedb/OpenProtocolInterpreter#54]
`OpenProtocolInterpreter.Converters`, class `StrategyOptionsConverter`, `ConvertToBytes()`:

This method creates an output of 10 bytes. But correct is 5 bytes. Maybe a block copy bug from `TighteningErrorStatusConverter.cs`, which uses 10 bytes. This problem makes `Mid0061` unusable. :(

```csharp
// byte[] bytes = new byte[10];        // wrong
byte[] bytes = new byte[5];            //correct

// bytes[2] = bytes[3] = bytes[4] = bytes[5] = bytes[6] = bytes[7] = bytes[8] = bytes[9] = 0;   // wrong
bytes[2] = bytes[3] = bytes[4] = 0;                                                             //correct
```

**Comment by Rickedb** [comment]
As you suppose, yep probably took `TighteningErrorStatusConverter.cs` as a reference, thank you for submiting the issue!
