### ISSUE TITLE
LEFT_PADDED missing in Mid0002

### ISSUE THREAD

**Issue by IngeRuppio** [Rickedb/OpenProtocolInterpreter#57]
A while ago, you added `LEFT_PADDED` to `CELL_ID` and `CHANNEL_ID` - fine, these were missing in earlier versions.
But `SYSTEM_TYPE` and `SYSTEM_SUBTYPE` do need `LEFT_PADDED` as well - please add these!

**Comment by Rickedb** [comment]
Couldn't achieve the same behaviour here. Both seems to be left padded in the current version:

```csharp
...
{
    5, new  List<DataField>()
            {
                new DataField((int)DataFields.SYSTEM_TYPE, 163, 3, '0'),
                new DataField((int)DataFields.SYSTEM_SUBTYPE, 168, 3, '0')
            }
},
```

**Comment by IngeRuppio** [comment]
I misused these fields to transfer some private identifiers. Depending on the number of digits of the values, they got messed up.
