### ISSUE TITLE
TotalParameterSets in Mid0011 is always 0

### ISSUE THREAD

**Issue by IngeRuppio** [Rickedb/OpenProtocolInterpreter#60]
While trying to fix Issue #59 I found the property `TotalParameterSets` to be always 0.
If I received a `Mid0011`, `ParameterSets` is fine and of course `ParameterSets.Length` holds the number of entries.
But `TotalParameterSets` is 0 and therefore cannot be used. 
I tried to fix Issue #59 by setting the Size to `TotalParameterSets * 3`, but as it is always 0, it didn't work.

**Comment by Rickedb** [comment]
With this modification, `TotalParameters` will always be a representation of total items in `ParameterSets` list. However if somehow the controller is sending a wrong number of parameters in TotalParameters' field, it won't consider!
This might cause some misunderstanding when diagnosing any problem. 

There is no way to bind it to both, TotalParameters' field and list itself, but it's better to bind it to the real list than to a arbitrary value.
