### ISSUE TITLE
Tightening Subscribe Response MID0061

### ISSUE THREAD

**Issue by storealutes** [Rickedb/OpenProtocolInterpreter#8]
The MID0061 object through MIDIncome will not update to new data. When I run more than one tightening the tightening information received in the onTighteningReceived function is always the same as the first tightening received. I have looked at the raw data coming in the logs and I can see they are different and the Tightening ID is increasing in the raw data string but the new data is not being parsed into the object.

I am using Mid0060 revision 6 because my controller reports that revision 7 is not available.

**Comment by Rickedb** [comment]
Sorry for the delay. I will check it out, I might figure out on my own, but can you exemplify the way you are using it?

About the revision, as far as I know, usually depends on controller's firmware, but there is no problem using the library with another revision.

**Comment by Rickedb** [comment]
I've checked, maybe there is a problem with MessagesTemplate possibly using the same instance of MID to parse.

If you could provide the way you're using it, it would be awesome. (if is different from the sample)

**Comment by Rickedb** [comment]
I could simulate exactly your problem, I'll be taking care of this and release a new version

**Comment by Rickedb** [comment]
Solution will be provided in version 3.X.X, please keep an eye here (or on NuGet)
