### ISSUE TITLE
MID0065 - DataFields of TorqueStatus and AngleStatus wrong set 

### ISSUE THREAD

**Issue by LGTCO** [Rickedb/OpenProtocolInterpreter#80]
[https://github.com/Rickedb/OpenProtocolInterpreter/blob/d57be03fcc47e67fc3a7402366d0798204991a72/src/OpenProtocolInterpreter/Tightening/Mid0065.cs](url)
![chrome_d9O2U3eVuW](https://user-images.githubusercontent.com/23730062/137252971-a74c74cf-03df-4e2d-bdb1-973d30fbbfc5.png)

**Comment by Rickedb** [comment]
Fixed at version `3.6.2`, please download it at NuGet and thanks for submiting the issue.
