### ISSUE TITLE
MId 0061 Torque values are not correct

### ISSUE THREAD

**Issue by BennyBread** [Rickedb/OpenProtocolInterpreter#82]
If you receive an tightening result MID0061 the torque values are not converted. they are still "value *100 as integer".
I think it would be great to capsule the restoration of the original value in the mid 61 deserialization.
So the the values which can be read of the mid variable instance would be "correct" and from application side no knowledge about the value conversion is needed.

This is more or less an feature request.

**Comment by tecnologic-srl-roberto-guerzoni** [comment]
Mid mid0061= OpenProtocolInterpreter.Parse( receivedMid0061.Pack() );
mid0061.Torque is a double value

**Comment by Rickedb** [comment]
Closed due to inactivity
