### ISSUE TITLE
not able to make a job request

### ISSUE THREAD

**Issue by rolandk76** [Rickedb/OpenProtocolInterpreter#85]
Hi, thanks for the great solution...
I am using your windows Forms Example, but I always get an Error back if I try to send a job in the sample...:

Sending job <1> to controller!
Sending message: 00220038001         
Response: 00260004    0000    003801
Job refused by controller under error code <1> (INVALID_DATA)!

can some pls help me in this case...
thanks!

**Comment by xGusu** [comment]
Hi . 
Are you connected to controller ? Keep alive is working?

**Comment by rolandk76** [comment]
yes I am, it is only an issue if I want to send a job

**Comment by xGusu** [comment]
At the end of message do you add 0x00 Character

**Comment by rolandk76** [comment]
thanks for answer, yes i use it in that way with your sample app... but I am not able to run the SendJobCommand without the error I get back from the controller... maybe the job informations are missing, that it is not possible to select one?

**Comment by xGusu** [comment]
I never ask what controller are you using?

Gustav Vanderdi
________________________________

**Comment by rolandk76** [comment]
it is an Power Focus 6000

**Comment by xGusu** [comment]
this is a byte array of the message . yours look the same ?
48 48 50 50 48 48 51 56 48 48 49 32 32 32 32 32 32 32 32 32 48 49 0

?

Don't know what to say. Use wireshark to capture the package and make a byte compare . if the message is like in the documentation and still not work ask maybe Atlas Copco support. for the moment i don't have any controller to test.

**Comment by Rickedb** [comment]
@rolandk76  any updates here?

**Comment by Rickedb** [comment]
Closed due to inactivity
