### ISSUE TITLE
Error codes missing

### ISSUE THREAD

**Issue by eduardomantovani** [Rickedb/OpenProtocolInterpreter#91]
I'm working on an Open Protocol Gateway for a  wireless tool and the error code 27 (Tool is inaccessible) could be interesting for me. 
Unfortunately, this error code (27) is not available in the ERROR enum, as some other error codes. Do you have a reason to keep those error codes out of the enum? Or it could be included in a next version?
Thank you for the great job!

**Comment by Rickedb** [comment]
Hello @eduardomantovani, you have a good point. At first sight I thought that error codes were kind of immutable or would not change in such a high frequency. However that's not reality.

I'm probably going to modify every enum propertu into a `int` field, which seems to give more flexibility for everyone and just update enum for documentation purpose or to increase code readability (like `HttpClient` implementation).

With this, we must not block any user when using the library.

**Comment by Rickedb** [comment]
I will update `Error` with the missing error code to provide more readability, but not switch to `int` as mentioned before.

However, despite the enum doesn't exists, C# still allow us to cast an unavailable int to the desired enum:

```csharp
var test = (Error)27;
if((int)test == 27)
{

}
```

So this will work as well:
```csharp
if((int)mid4.ErrorCode == 27)
{

}
```
